### PR TITLE
A few small changes

### PR DESCRIPTION
**Pull request by megastep**
Includes a safety check for the transaction receipt.

### CODE REVIEW

**Comment by mtabini** [comment]
I'm not sure that an exception on an empty receipt is a good idea. What if we switched to an error instead? Either way, it's pretty unlikely, but I don't know that a crash in those cases is good.

**Comment by megastep** [comment]
Yeah, well either way works for me. I'm generally not a big fan of Objective-C exceptions, but I wanted to keep it consistent with the rest of your code. It was just puzzling that nothing would go wrong when I ended up an empty receipt, which seems to be a common case when restoring transactions on iOS 4. So as long as we inform the developer when that happens, then it should be ok!

**Comment by mtabini** [comment]
OK, I'm going to switch this to an error before merging, then. Thanks!

**Comment by mtabini** [comment]
OK, committed, and I got rid of CCCrypt in favour of a custom version of Blowfish.

**Comment by megastep** [comment]
Very cool. No longer crashes because of Blowfish, however I'm getting some 403 validation errors from the server now on iOS 4, I have to look at what exactly is going on.

**Comment by mtabini** [comment]
On 2012-07-31, at 1:53 PM, Stephane Peter reply@reply.github.com wrote:

> Very cool. No longer crashes because of Blowfish, however I'm getting some 403 validation errors from the server now on iOS 4, I have to look at what exactly is going on.

Odd. From the server side, the only two things that will give you a 403 are a missing or incorrect API key, or an expired transaction—neither of which should be affected by the encryption mechanism. Let me know if you find out what's causing the problem.

**Comment by megastep** [comment]
Oh, it could be expired transactions maybe. The system tries to restore previously failed transactions every time the app starts, though I think it should create a new transaction for these every time. Also the same thing when trying to do a new IAP. I'm gonna compare what is going on between iOS 4 and 5 devices.

**Comment by megastep** [comment]
Well the error message returned seems to be for an expired transaction :

{"code":403,"message":"Transaction expired.","data":[]}

I'm a bit unclear about what this means exactly - is there just a very small amount of time for which the transaction can be verified? Or is this indicative of something going on with Apple? I'm just wondering if the problem might just be that my old iPhone 3G on iOS 4.2 is just too slow to process all this for your server. The same code seems to work fine on newer devices.

**Comment by mtabini** [comment]
Yes—when you send in a receipt verification request, the system only accepts it if it is timestamped within one minute of the current time (and vice versa). One minute is plenty even for the slowest of phones—is it possible that your phone's time is incorrect or set to the wrong timezone?

**Comment by megastep** [comment]
You're right, that was the problem - it worked after I adjusted the time!

However this can be a very real problem in case of small discrepancies with time sync. This phone uses network sync but not from the cell towers (it's no longer active and I basically use it like an iPod touch). Yet the supposedly synced time was about 2 minutes behind my other devices. I had to turn it on and off the setting for automatic sync to force it to get the correct time. I assume when it's not in use it doesn't stay connected to my WiFi network and it may not be checking the time often enough to keep truly in sync.

I imagine the same thing may be happening with iPod touches or iPad that may only have intermittent network connections to do the time sync. Maybe it's not very usual but it obviously happens...

Maybe we need to rely less on the absolute time being correct, like using a first connection as a reference? Or at least consider increasing it beyond that one minute and making the error reporting more explicit about what the problem might be (403 is too vague unless you look at the body of the error).

**Comment by mtabini** [comment]
It's an iOS4-only issue—it was a bug with older versions of the operating system. But we will simply increase the timeout to ten minutes; anything more than that, and we open things up to time-based attacks.

**Comment by megastep** [comment]
OK, well that should work. I'd also like to see more accurate reporting for when this situation happens so we can warn the user to maybe double-check their time settings (basically give a bit more than just the status code, especially since more info is in the JSON). I might be able to put a quick patch together for this...

**Comment by mtabini** [comment]
I agree. I'm going to make that a different error code; stay tuned.

**Comment by mtabini** [comment]
OK, the server now returns 410 errors on expired transactions. I'm going to add a property to the SDK to indicate that error condition.

**Comment by mtabini** [comment]
Done—there is now a clientServerTimeMismatch property in BBXIAPTransaction that is flipped on if the server throws a 410.

**Comment by megastep** [comment]
Very nice. I'll change my app to check for this. Maybe time to release a new beta of the SDK? :)

**Comment by mtabini** [comment]
Indeed. New beta out (the library is < 1MB now!) and documentation pushed to the live site. Thanks for your help!

**Pull request merged**
